Add option to set the Karaf logfile
Add barclamp attribute to set the logfile for the Karaf container.
This also fixes the JSON schema validation problems when trying to
apply the barclamp since at least one attribute is required by crowbar.

~$ kwalify -f chef/data_bags/crowbar/template-opendaylight.schema
ERROR: [/mapping/attributes/mapping/opendaylight/mapping] required at least one element.

Signed-off-by: Markos Chandras <mchandras@suse.de>